# -*- coding: utf-8 -*-
"""multi_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfdu2wvKKqK4tqIvI3AGHXUfRtIwydHe
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
import torch
from torch import nn
from sklearn.metrics import accuracy_score

from numpy.random import random_integers
X , Y= make_blobs(n_samples=1000 , n_features=2 , centers=4 ,cluster_std=1.5 ,random_state=42 )

x_blob = torch.from_numpy(X).type(torch.float)
y_blob = torch.from_numpy(Y).type(torch.LongTensor)

X_train  , X_test , Y_train ,Y_test = train_test_split(x_blob , y_blob, train_size=0.8, random_state=42)
X_train.shape , X_test.shape , Y_train.shape , Y_test.shape

plt.figure(figsize=(10,7))
plt.scatter(x_blob[:,0],x_blob[:,1],c=y_blob, cmap=plt.cm.RdYlBu)

# Model
model = nn.Sequential(
    nn.Linear(in_features=2 , out_features=8),
    nn.ReLU(),
    nn.Linear(in_features= 8 , out_features= 8 ),
    nn.ReLU(),
    nn.Linear(in_features= 8 , out_features= 4)

)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(params= model.parameters() , lr=0.1)

# Raw outputs
model.eval()
with torch.inference_mode():
  y_logits= model(X_test)
y_logits[:10]

y_pred_probs=torch.softmax(y_logits, dim=1)
y_preds=torch.argmax(y_pred_probs, dim=1)
y_preds[:10]

# training loop
torch.manual_seed(42)
epochs= 100
for epoch in range(epochs):
  model.train()
  y_logits= model(X_train)
  y_pred= torch.softmax(y_logits, dim=1).argmax(dim=1)

  loss= loss_fn(y_logits , Y_train)
  acc= accuracy_score(Y_train , y_pred)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  model.eval()
  with torch.inference_mode():
    y_test_logits= model(X_test)
    y_test_preds= torch.softmax(y_test_logits, dim=1).argmax(dim=1)

    test_loss= loss_fn(y_test_logits, Y_test)
    test_acc= accuracy_score(y_test_preds, Y_test)

    if epoch % 10 ==0:
      print(f"Epoch : {epoch}  | loss : {loss:.4f} | acc : {acc:.2f}%  | test loss {test_loss:.4f} | test acc {test_acc:.2f}%")

# making the prediction
model.eval()
with torch.inference_mode():
  y_logits= model(X_test)
  y_pred_probs= torch.softmax(y_logits , dim=1)
y_pred_probs[:10]

y_pred = torch.argmax(y_pred_probs , dim=1)
print(Y_test)

y_pred

accuracy_score(Y_test , y_pred)

def plot_decision_boundary(model, X, y):

    # Convert tensors to numpy
    X = X.detach().numpy()
    y = y.detach().numpy()

    model.eval()

    # Create meshgrid
    x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
    y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5

    xx, yy = np.meshgrid(
        np.linspace(x_min, x_max, 200),
        np.linspace(y_min, y_max, 200)
    )

    # Prepare grid for model
    grid = np.c_[xx.ravel(), yy.ravel()]
    grid_tensor = torch.from_numpy(grid).type(torch.float)

    # Make predictions
    with torch.inference_mode():
        logits = model(grid_tensor)
        preds = torch.softmax(logits, dim=1).argmax(dim=1)

    preds = preds.reshape(xx.shape).detach().numpy()

    # Plot
    plt.figure(figsize=(8,6))
    plt.contourf(xx, yy, preds, cmap=plt.cm.RdYlBu, alpha=0.7)
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.RdYlBu)
    plt.title("Decision Boundary")
    plt.show()