# -*- coding: utf-8 -*-
"""non_linear_ classification.ipynb

Automatically generated by Colab.


Original file is located at
    https://colab.research.google.com/drive/1qSLLe5rZeNgdY-LRgA_wa7nuiLg8XfaC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from torch import nn
from sklearn.datasets import make_circles

x,y = make_circles(n_samples=1000,
                   noise=0.03,
                   random_state=42)
plt.scatter(x[:,0],x[:,1],c=y, cmap=plt.cm.RdYlBu);

# data to tensors
X=torch.from_numpy(x).type(torch.float)
y=torch.from_numpy(y).type(torch.float)

# split the data
from  sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y , train_size=0.8, random_state=42)

# making the model with non linearity
model=nn.Sequential(nn.Linear(2,10),
                    nn.ReLU(),
                    nn.Linear(10,10),
                    nn.ReLU(),
                    nn.Linear(10,1)
)

# GPU
device='cuda' if torch.cuda.is_available() else 'cpu'
device

X_train=X_train.to(device)
X_test=X_test.to(device)
y_train=y_train.to(device)
y_test=y_test.to(device)

# loss + optimizer
loss_fn=nn.BCEWithLogitsLoss()
optimizer=torch.optim.SGD(params=model.parameters(), lr=0.1)

from sklearn.metrics import accuracy_score

# Move model to device (GPU if available)
model.to(device)

# training loop
epoch=1000
for i in range(epoch):
  model.train()
  y_logits=model(X_train).squeeze()
  y_pred=torch.round(torch.sigmoid(y_logits))
  loss=loss_fn(y_logits,y_train)
  acc=accuracy_score(y_pred.detach().cpu(),y_train.detach().cpu())
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  model.eval()
  with torch.inference_mode():
    
    X_test = X_test.to(device)
    y_test = y_test.to(device)
    test_logits=model(X_test).squeeze()
    test_pred=torch.round(torch.sigmoid(test_logits))
    test_loss=loss_fn(test_logits,y_test)
    test_acc=accuracy_score(test_pred.detach().cpu(),y_test.detach().cpu())
    if i % 100 == 0:
      print(f"Epoch: {i} | Loss: {loss:.4f} | Acc: {acc:.2f} | Test_loss: {test_loss:.4f} | Test Acc {test_acc:.2f}%")

# Making the predictions
model.eval()
with torch.inference_mode():
  y_preds=torch.round(torch.sigmoid(model(X_test))).squeeze

# Making the predictions correctly
model.eval()
with torch.inference_mode():
    y_preds = torch.round(torch.sigmoid(model(X_test))).squeeze()  # added parentheses

# Move tensors to CPU and convert to numpy for plotting
X_test_np = X_test.cpu().numpy()
y_test_np = y_test.cpu().numpy()

# Create a meshgrid for decision boundary
h = 0.01
x_min, x_max = X[:,0].min() - 0.1, X[:,0].max() + 0.1
y_min, y_max = X[:,1].min() - 0.1, X[:,1].max() + 0.1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                     np.arange(y_min, y_max, h))

# Flatten and convert to torch tensor
grid = torch.from_numpy(np.c_[xx.ravel(), yy.ravel()]).float().to(device)
with torch.inference_mode():
    Z = torch.sigmoid(model(grid))
    Z = torch.round(Z).cpu().numpy().reshape(xx.shape)

# Plot decision boundary + test points
plt.figure(figsize=(10,6))
plt.contourf(xx, yy, Z, alpha=0.3, cmap=plt.cm.RdYlBu)
plt.scatter(X_test_np[:,0], X_test_np[:,1], c=y_test_np, cmap=plt.cm.RdYlBu, edgecolors='k')
plt.title("Decision Boundary & Test Points")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()