# -*- coding: utf-8 -*-
"""california_housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uzz2AUd9KBkHHKKADXxECbcilL0uTubO
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import fetch_california_housing
import torch
from torch import nn

#using the california dataset
data=fetch_california_housing()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['target']=data.target
df.head(10)

# Assigning the values
x=df.drop('target',axis=1).values
y=df['target'].values

# Splitting data into the test / train
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.8,random_state=42)

from numpy.random import standard_cauchy
#Normalize values
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
X_train_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)
X_train_scaled

# Converting the numpy to the tensors
X_train_tensor=torch.tensor(X_train_scaled,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test_scaled,dtype=torch.float32)
y_train_tensor=torch.tensor(Y_train,dtype=torch.float32).view(-1,1)
y_test_tensor=torch.tensor(Y_test,dtype=torch.float32).view(-1,1)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# To CUDA
X_train_tensor = X_train_tensor.to(device)
X_test_tensor  = X_test_tensor.to(device)
y_train_tensor = y_train_tensor.to(device)
y_test_tensor  = y_test_tensor.to(device)

#Creating the siple regression model
model=nn.Sequential(
    nn.Linear(X_train_tensor.shape[1],128),
    nn.ReLU(),
    nn.Linear(128,64),
    nn.ReLU(),
    nn.Linear(64,32),
    nn.ReLU(),
    nn.Linear(32,16),
    nn.ReLU(),
    nn.Linear(16,1)
)

#Trining setup
loss_fn=nn.MSELoss()
critation=torch.optim.Adam(model.parameters(),lr=0.001)

#dara loader for the batches
from torch.utils.data import DataLoader,TensorDataset
ds=TensorDataset(X_train_tensor,y_train_tensor)
Train_loader=DataLoader(ds,batch_size=64, shuffle=True)

# Traning the data
model.to(device)
epoches=200
for i in range(epoches):
  for X_train_tensor,y_train_tensor in Train_loader:
    X_train_tensor=X_train_tensor.to(device)
    y_train_tensor=y_train_tensor.to(device)
    y_pred=model(X_train_tensor)
    loss=loss_fn(y_pred,y_train_tensor)
    critation.zero_grad()
    loss.backward()
    critation.step()
  if (i+1) % 50 == 0:
        print(f"Epoch {epoches+1}, Loss = {loss.item():.4f}")

#Cheaking the model accuracy
from sklearn.metrics import r2_score,mean_absolute_error
model.eval()
with torch.inference_mode():
  y_pred=model(X_test_tensor)
#now converting  to the nupy
y_pred=y_pred.cpu().detach().numpy()
y_test=y_test_tensor.cpu().detach().numpy()
print('R1_score',r2_score(y_test,y_pred))

#plotting the regression line
plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, alpha=0.5, color='blue', label='Predictions')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect prediction')
plt.xlabel("Actual Target")
plt.ylabel("Predicted Target")
plt.title("Predictions vs Actual Values")
plt.legend()
plt.show()