# -*- coding: utf-8 -*-
"""creating_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUomf4K7skrI2xmKHpWxpMCAl9tIJzk3
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import torch
from torch import nn
from sklearn.datasets import make_regression

# making the data set
x, y = make_regression(n_samples=500000, n_features=50, noise=0.1, random_state=42)
columns_name=['x'+str(i) for i in range(50)]
df = pd.DataFrame(x, columns=columns_name)
df['target']=y
x=df.drop('target',axis=1)
x=x.values
y=df['target'].values

# splitting the data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=0.9,random_state=42)

# scalinn the values
from sklearn.preprocessing import StandardScaler
X_scalar=StandardScaler()
X_train=X_scalar.fit_transform(X_train)
X_test=X_scalar.transform(X_test)

#converting the numpy to tensors
X_train_tensor=torch.tensor(X_train,dtype=torch.float32)
X_test_tensor=torch.tensor(X_test,dtype=torch.float32)
Y_train_tensor=torch.tensor(Y_train,dtype=torch.float32).view(-1,1)
Y_test_tensor=torch.tensor(Y_test,dtype=torch.float32).view(-1,1)

#GPU
device= torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device :- ",device)

#Converting tensors to GPU usage
X_train_tensor=X_train_tensor.to(device)
X_test_tensor=X_test_tensor.to(device)
Y_train_tensor=Y_train_tensor.to(device)
Y_test_tensor=Y_test_tensor.to(device)

#Creating the model
model=nn.Sequential(
    nn.Linear(50,256),
    nn.ReLU(),
    nn.Linear(256,128),
    nn.ReLU(),
    nn.Linear(128,64),
    nn.ReLU(),
    nn.Linear(64,1)
)

fn_loss=nn.MSELoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)

# Dataloader
from torch.utils.data import TensorDataset,DataLoader
train_data=TensorDataset(X_train_tensor,Y_train_tensor)
loader=DataLoader(train_data,batch_size=3000,shuffle=True)

model.to(device)
epoches=10
for i in range(epoches):
    for x,y in loader:
      x=x.to(device)
      y=y.to(device)
      y_pred=model(x)
      loss=fn_loss(y_pred,y)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

#Cheaking the model accuracy
from sklearn.metrics import r2_score,mean_squared_error
model.eval()
with torch.inference_mode():
    y_pred=model(X_test_tensor)
    y_pred=y_pred.detach().cpu().numpy()
    y_test=Y_test_tensor.detach().cpu().numpy()
    print("R2 Score :- ",r2_score(y_test,y_pred))
    print("MSE :- ",mean_squared_error(y_test,y_pred))