# -*- coding: utf-8 -*-
"""image_tensor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQ8tjbj-z8nQxgsD6uw9DjD3S1RFpIp0
"""

import torch
image_tensor=torch.rand(224,224,3)
print(image_tensor)
print(image_tensor.shape)
print(image_tensor.ndim)

range=torch.arange(start=1,end=10,step=2)
range

ran=torch.tensor([3,6,9],
                 dtype=float,
                 device='cpu',
                 requires_grad=False)
ran,ran.shape,ran.device